### ISSUE TITLE
Rename to astropy-healpix

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-healpix#10]
If there is interest from the rest of the astropy community to move this to the astropy organization, I propose that we rename the repository and package to astropy-healpix.

**Comment by cdeil** [comment]
@astrofrog - I've made a proposal in e364fe8 in  #47 how I would chose names / do the release:

![screen shot 2017-09-30 at 13 21 56](https://user-images.githubusercontent.com/852409/31045382-9bc8b290-a5e2-11e7-9e3a-e96410d8d29a.png)

It's the naming scheme I would prefer and also the minimal amount of work, given that the name of this repo, this package and the PyPI name and RTD name can stay as `healpix` as-is, and only a conda-forge package by the name of `astropy-healpix` needs to be added. It's also equivalent to what we did for `regions`.

That said, I don't care strongly about names, and @astrofrog - if you were willing to do renames to whatever you prefer, so that we can get a v0.1 release out today or at least soon, then please just go ahead.

**Comment by astrofrog** [comment]
@cdeil - those kinds of inconsistencies bug me... For regions it's actually different since the RTD name is also different from the package (in fact I can't remember who I was speaking to but they said regions should have been called astropy-regions throughout).

This is also going to be an issue when releasing - we will then have to announce 'healpix' but then that might lead to confusion. I do think we should switch to astropy-healpix throughout, and I'm happy to do all the renaming.

One thing we could do to minimize pain is *also* switch this repo to the astropy organization today since then we avoid having to fix all the references twice. What do you think?

**Comment by cdeil** [comment]
> regions should have been called astropy-regions throughout

Not possible, not a valid Python symbol one can import.
It's the same problem / confusing the `sklearn` / `scikit-learn` and other `scikit-` or `astropy-` packages have.
I'm sure you know, but just to be clear, doing the `scikit.learn` or `astropy.healpix` via trickery is the worst, let's not do that.

> One thing we could do to minimize pain is also switch this repo to the astropy organization today since then we avoid having to fix all the references twice. What do you think?

Please go ahead (and take over #47 and just put all the names (including RTD and repo) you prefer!

We should do all re-location and re-naming before the v0.1 release and then never change it again (until the point / if where we propose this package for inclusion in Astropy core).

**Comment by astrofrog** [comment]
> Not possible, not a valid Python symbol one can import

Ah sorry I should have clarified - as with other packages that have a - in the name, the python module would have a _. Really scikit-learn should be scikit_learn for the import.

I completely agree about not doing astropy.healpix now. Note however that if we do astropy_healpix for now (for the module name) and then merge into astropy later, it will be an easy fix for users, who can just replace astropy_healpix with astropy.healpix.

**Comment by cdeil** [comment]
So you want to do `astropy_healpix` everywhere?
Change Python package name, Git repo name, RTD name, register new PyPI name?
OK, go ahead.

---

> Really scikit-learn should be scikit_learn for the import.

I think most packages that chose one of the `scikit-` names regretted that, and it's no longer recommended to prefix packages with `scikit-` or `scikit_`. So I would say this statement is just an opinion, and it should rather be " scikit-learn could have been scikit_learn for the import".

I don't think it matters so much for this package, but just in case you plan to do this for many packages that use Astropy, just be aware of the drawbacks. `import healpix` is nicer / faster to type than `import astropy_healpix`. There's many packages where it's not clear if they will ever be migrated into AStropy core or will be accepted as Astropy affiliated packages, so starting out with `astropy` in the name is pretty presumptuous on part of the guy starting the package. Renames are painful.

---

I'll shut up now and let you go on with making the renames / making a first release.

**Comment by astrofrog** [comment]
Just to clarify, I don't actually think we should use ``astropy-`` for all packages (and my comment about regions was only half-serious), and I agree ``healpix`` is nicer to import. However I think this is an exceptional case where there is already HEALPix and healpix so adding ``astropy-`` to the front is to make it clear this is the astropy version of HEALPix. So I'm mainly just trying to avoid confusion here, and this is a special case where the astropy coordinators have said they are ok with astropy-healpix as a name.

**Comment by astrofrog** [comment]
> I think there's no reason to show healpix.core_cython in the public API docs, i.e. there should never be a use case to call those functions from external packages, instead our healpix and healpix.core and healpix.healpy exposes all functionality in a better way?

I went back and forth on this and at the end of the day I agree with you - I think we can expose it some day *if* there are significant performance benefits (which I don't think there are at the moment)

> Wouldn't it be nicer to expose the functions from healpix.core directly in the healpix namespace? The term "core" is really jargon we use in Astropy or maybe other Python packages as well, but it's not something that we should make end-users type in their import statements, no?

The intent here was actually that the recommended API is actually to use the high-level class(es), so users wouldn't actually need to import them. However, if you feel strongly that they should be able to use these functions without the classes, then feel free to import them into the top-level (I don't have a strong opinion here)

> The biggest question in terms of usability / docs I have is if we really need to teach users about two classes, or if they can be merged into one, by having a default frame=None, and how the FITS I/O is implemented.

So if the frame is not given, the ``*_skycoord`` methods wouldn't work, right? (I mean they would give a suitable error message). If so then I'm fine with merging the two classes.

I think we might as well do this for 0.1 since these are easy changes, and better to start off with a simple API and expand than remove things later I think. Do you want to open a PR for this?

I'll be available later this afternoon too if there are things we do need to discuss.

**Comment by astrofrog** [comment]
Oh by the way, one idea would be to simply move the automodapi statements for healpix.core and healpix.core_cython to this page:

http://healpix.readthedocs.io/en/latest/low_level_api.html

Then the main API on the front page is a single class - clean! :star:

**Comment by astrofrog** [comment]
Similarly, the API docs for the healpy interface can go here:

http://healpix.readthedocs.io/en/latest/healpy_compat.html

**Comment by cdeil** [comment]
Is there a single use case where someone has to or should call into the functions in healpix.core_cython`?

If not, I would suggest to delete this automodapi
http://healpix.readthedocs.io/en/latest/api.html#module-healpix.core_cython
and to change this page to not mention it: http://healpix.readthedocs.io/en/latest/low_level_api.html

---

Similarly concerning http://healpix.readthedocs.io/en/latest/api.html#module-healpix.core : are there cases where one has to / should call these functions instead of instantiating a class?

I think yes, e.g. `interpolate_bilinear_lonlat` or even just the `nside_to_npix` helper that doesn't require an order. We could choose a default order for the class, then the need to expose  these separate functions to end-users becomes smaller.
My suggestion here would be still that we just expose those functions in the top-level namespace, to avoid having them in "core" which is a weird term, and one could consider the class the primary core interface.

---

> So if the frame is not given, the *_skycoord methods wouldn't work, right? (I mean they would give a suitable error message). If so then I'm fine with merging the two classes (I wouldn't want frame defaulting to say ICRS). I think a single class would be cleaner.

Yes, exactly. The main motivation to have a single class is that it's much nicer for end-users. Otherwise they will always be confused at least at the start which class they should import or learn, and then when you notice that you have / need a frame for a given script, you have to go back and adjust the import. I have no other argument for one class except that I think it's a more user-friendly API.

---

Yes, I can open a PR if it helps and you haven't started the big rename yet.

**Comment by astrofrog** [comment]
I'm fine with just hiding the Cython interface, and importing the core functions into the top-level of the package. I'll wait until you do this PR to rename things.

**Comment by astrofrog** [comment]
Done!
