### ISSUE TITLE
BLD: pp39 wheels fail to build

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy-healpix#216]
I noticed builds for pypy 3.9 had been failing recently
[example logs](https://github.com/astropy/astropy-healpix/actions/runs/9442289521/job/26004215978)
Initially I thought this was because of an incompatibility with numpy 2.0.0 (just released 3 days ago), but the jobs have actually been failing for much longer (3 months).
I'm opening this ticket to raise awareness on this; I can also try to solve it myself if requested.

**Comment by lpsinger** [comment]
It's actually failing to build Numpy which is a build requirement. It's trying to build Numpy from source for PyPy on i686 (32-bit). Numpy doesn't publish any 32-bit wheels for Linux right now. I suspect that is intentional. Do you need 32-bit support? If not, then I suggest that we skip building for 32-bit, or at least building for 32-bit PyPy.

**Comment by neutrinoceros** [comment]
I do not need it, I just noticed this while inspecting how well astropy packages handled numpy 2.0 now that it's released.
Skipping this target seems fine to me if numpy itself isn't building for it either.
