### ISSUE TITLE
Use legacy Numpy formatting in doctests

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy-healpix#79]
@cdeil, I noticed that you changed formatting of string representations of Numpy arrays in docstrings in 31fe342fa7b36b986c6054e057321ab05b3756fb. FYI, you probably need to implement something like healpy/healpy#440 so that the doctests work with both old and new versions of Numpy.

**Comment by cdeil** [comment]
I added `doctest-skip-all` because overall doctests for floats are so painful because of the representation issues. I.e. avoid repr-based asserts, at the cost of not having auto doctest example tests, just use normal tests and have a bit of duplication with the docs.
But that's must my opinion to go that way, others prefer to keep using doctests.

Thoughts?

**Comment by astrofrog** [comment]
I prefer to keep doctests as they do ensure that the docs themselves are correct, but I'm fine with changing to always explicitly printing rather than comparing the repr, which I think is what @lpsinger was suggesting to do anyway to fix the 32-bit doctests.

**Comment by lpsinger** [comment]
Oh right. This was fixed by #82. @astrofrog, the 32-bit issue is #81.
